"""
Fuzzer Manager — AI-guided parallel HTTP fuzzing.

Key Principles (CRITICAL):
1. LLM GENERATES ALL PAYLOADS - No static lists
2. Tool only EXECUTES requests in parallel
3. Returns DATA (response codes, times, sizes) not commands
4. LLM decides what payloads to try based on context
"""

from __future__ import annotations

import hashlib
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from phantom.tools.proxy.proxy_manager import get_proxy_manager


@dataclass
class FuzzRequest:
    """A single fuzz request to execute."""

    id: str
    method: str
    url: str
    payload: str
    injection_point: str  # Where the payload goes: "param", "header", "body", "path"
    param_name: str | None = None  # For param/header injection
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


@dataclass
class FuzzResult:
    """Result of a fuzz request execution."""

    request_id: str
    payload: str
    status_code: int | None
    response_time_ms: float
    response_length: int
    error: str | None = None
    interesting_markers: list[str] = field(default_factory=list)
    completed_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "request_id": self.request_id,
            "payload": self.payload,
            "status_code": self.status_code,
            "response_time_ms": self.response_time_ms,
            "response_length": self.response_length,
            "error": self.error,
            "interesting_markers": self.interesting_markers,
            "completed_at": self.completed_at,
        }


class FuzzerManager:
    """
    Manages parallel fuzzing execution.

    This is a pure executor - LLM provides payloads, we execute them.
    """

    _instance: FuzzerManager | None = None
    _instance_lock = threading.Lock()

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._results: dict[str, list[FuzzResult]] = {}  # batch_id -> results
        self._max_workers = 10  # Parallel request limit

    @classmethod
    def _get_instance(cls) -> FuzzerManager:
        """Get singleton instance (thread-safe)."""
        if cls._instance is None:
            with cls._instance_lock:
                if cls._instance is None:
                    cls._instance = FuzzerManager()
        return cls._instance

    def execute_batch(
        self,
        base_url: str,
        method: str,
        payloads: list[str],
        injection_point: str,
        param_name: str | None = None,
        headers: dict[str, str] | None = None,
        timeout_seconds: float = 10.0,
        follow_redirects: bool = False,
    ) -> dict[str, Any]:
        """
        Execute a batch of fuzz requests in parallel.

        Args:
            base_url: The target URL (may contain {FUZZ} marker for path injection)
            method: HTTP method (GET, POST, etc.)
            payloads: List of payloads generated by LLM
            injection_point: Where to inject - "param", "header", "body", "path"
            param_name: Name of parameter/header to fuzz (required for param/header)
            headers: Additional headers to include
            timeout_seconds: Request timeout
            follow_redirects: Whether to follow redirects

        Returns:
            Batch execution results with timing and response data
        """
        batch_id = self._generate_batch_id(base_url, payloads)

        # Build requests
        requests: list[FuzzRequest] = []
        for idx, payload in enumerate(payloads):
            request_id = f"{batch_id}-{idx}"
            requests.append(
                FuzzRequest(
                    id=request_id,
                    method=method.upper(),
                    url=base_url,
                    payload=payload,
                    injection_point=injection_point,
                    param_name=param_name,
                )
            )

        # Execute in parallel
        results = self._execute_parallel(
            requests=requests,
            headers=headers or {},
            timeout_seconds=timeout_seconds,
            follow_redirects=follow_redirects,
        )

        # Store results
        with self._lock:
            self._results[batch_id] = results

        # Analyze and return
        return self._analyze_results(batch_id, results)

    def _generate_batch_id(self, base_url: str, payloads: list[str]) -> str:
        """Generate unique batch ID."""
        content = f"{base_url}-{len(payloads)}-{datetime.now(UTC).isoformat()}"
        return f"FUZZ-{hashlib.md5(content.encode()).hexdigest()[:8].upper()}"

    def _execute_parallel(
        self,
        requests: list[FuzzRequest],
        headers: dict[str, str],
        timeout_seconds: float,
        follow_redirects: bool,
    ) -> list[FuzzResult]:
        """Execute requests in parallel using ThreadPoolExecutor."""
        results: list[FuzzResult] = []

        with ThreadPoolExecutor(max_workers=self._max_workers) as executor:
            future_to_request = {
                executor.submit(
                    self._execute_single_request,
                    req,
                    headers,
                    timeout_seconds,
                    follow_redirects,
                ): req
                for req in requests
            }

            for future in as_completed(future_to_request):
                try:
                    result = future.result()
                    results.append(result)
                except Exception as e:
                    req = future_to_request[future]
                    results.append(
                        FuzzResult(
                            request_id=req.id,
                            payload=req.payload,
                            status_code=None,
                            response_time_ms=0.0,
                            response_length=0,
                            error=str(e),
                        )
                    )

        return results

    def _execute_single_request(
        self,
        request: FuzzRequest,
        headers: dict[str, str],
        timeout_seconds: float,
        follow_redirects: bool,
    ) -> FuzzResult:
        """Execute a single fuzz request."""
        start_time = datetime.now(UTC)

        try:
            manager = get_proxy_manager()

            # Build the request based on injection point
            if request.injection_point == "path":
                url = request.url.replace("{FUZZ}", request.payload)
                data = ""
            elif request.injection_point == "param":
                if not request.param_name:
                    raise ValueError("param_name is required for param injection")
                url = _upsert_query_param(request.url, request.param_name, request.payload)
                data = ""
            elif request.injection_point == "header":
                if not request.param_name:
                    raise ValueError("param_name is required for header injection")
                url = request.url
                data = ""
                headers = {**headers, request.param_name: request.payload}
            elif request.injection_point == "body":
                url = request.url
                data = request.payload
            else:
                raise ValueError(f"Invalid injection_point: {request.injection_point}")

            # Execute request through proxy path (with explicit policy fallback if configured).
            response_data = manager.send_simple_request(
                method=request.method,
                url=url,
                headers=headers,
                body=data,
                timeout=timeout_seconds,
                follow_redirects=follow_redirects,
            )

            if response_data.get("error"):
                raise RuntimeError(str(response_data.get("error")))

            status_code = response_data.get("status_code")
            response_body = str(response_data.get("body") or "")

            # Calculate response time
            end_time = datetime.now(UTC)
            response_time_ms = (end_time - start_time).total_seconds() * 1000

            # Check for interesting markers
            interesting = self._detect_interesting_markers(status_code, response_body)

            return FuzzResult(
                request_id=request.id,
                payload=request.payload,
                status_code=int(status_code) if isinstance(status_code, int) else None,
                response_time_ms=response_time_ms,
                response_length=len(response_body.encode("utf-8", errors="ignore")),
                interesting_markers=interesting,
            )

        except Exception as e:
            end_time = datetime.now(UTC)
            response_time_ms = (end_time - start_time).total_seconds() * 1000

            return FuzzResult(
                request_id=request.id,
                payload=request.payload,
                status_code=None,
                response_time_ms=response_time_ms,
                response_length=0,
                error=str(e),
            )

    def _detect_interesting_markers(self, status_code: int | None, response_text: str) -> list[str]:
        """
        Detect interesting response characteristics.

        Returns FACTS not commands - LLM decides what's interesting.
        """
        markers: list[str] = []

        # Status code anomalies
        if status_code == 500:
            markers.append("error_500")
        elif status_code == 403:
            markers.append("forbidden_403")
        elif status_code == 401:
            markers.append("unauthorized_401")
        elif status_code in (200, 201):
            markers.append("success_2xx")

        # Response content markers
        content_lower = response_text.lower()

        if "error" in content_lower or "exception" in content_lower:
            markers.append("error_in_response")
        if "sql" in content_lower and ("syntax" in content_lower or "mysql" in content_lower or "postgres" in content_lower):
            markers.append("sql_error")
        if "root:" in content_lower or "/etc/passwd" in content_lower:
            markers.append("lfi_success")
        if "<script" in content_lower or "javascript:" in content_lower:
            markers.append("xss_reflection")
        if "admin" in content_lower or "debug" in content_lower:
            markers.append("admin_debug_info")

        # Response timing anomalies (detected by LLM comparing results)
        # We just return the time, LLM can spot anomalies

        return markers

    def _analyze_results(
        self,
        batch_id: str,
        results: list[FuzzResult],
    ) -> dict[str, Any]:
        """
        Analyze batch results and return FACTS.

        LLM decides what's interesting based on the data.
        """
        if not results:
            return {
                "batch_id": batch_id,
                "total_requests": 0,
                "results": [],
            }

        # Group by status code
        by_status: dict[int | str, int] = {}
        for result in results:
            key = result.status_code if result.status_code else "error"
            by_status[key] = by_status.get(key, 0) + 1

        # Group by response length
        by_length: dict[int, int] = {}
        for result in results:
            by_length[result.response_length] = by_length.get(result.response_length, 0) + 1

        # Calculate timing stats
        times = [r.response_time_ms for r in results if r.response_time_ms > 0]
        avg_time = sum(times) / len(times) if times else 0.0
        min_time = min(times) if times else 0.0
        max_time = max(times) if times else 0.0

        # Find interesting results
        interesting_results = [r for r in results if r.interesting_markers]

        return {
            "batch_id": batch_id,
            "total_requests": len(results),
            "successful_requests": sum(1 for r in results if r.status_code),
            "failed_requests": sum(1 for r in results if r.error),
            "status_code_distribution": by_status,
            "response_length_distribution": by_length,
            "timing_stats": {
                "avg_ms": avg_time,
                "min_ms": min_time,
                "max_ms": max_time,
            },
            "interesting_count": len(interesting_results),
            "interesting_results": [r.to_dict() for r in interesting_results],
            "all_results": [r.to_dict() for r in results],
        }

    def get_results(self, batch_id: str | None = None) -> dict[str, Any]:
        """
        Get fuzzing results.

        Args:
            batch_id: Specific batch to retrieve, or None for all

        Returns:
            Results data
        """
        with self._lock:
            if batch_id:
                if batch_id not in self._results:
                    return {"error": f"Batch {batch_id} not found", "results": []}

                results = self._results[batch_id]
                return {
                    "batch_id": batch_id,
                    "result_count": len(results),
                    "results": [r.to_dict() for r in results],
                }

            # Return all batches
            all_batches = []
            for bid, results in self._results.items():
                all_batches.append({
                    "batch_id": bid,
                    "result_count": len(results),
                    "results": [r.to_dict() for r in results[:10]],  # First 10 only for summary
                })

            return {
                "total_batches": len(all_batches),
                "batches": all_batches,
            }

    def clear_results(self, batch_id: str | None = None) -> dict[str, Any]:
        """
        Clear fuzzing results.

        Args:
            batch_id: Specific batch to clear, or None for all

        Returns:
            Summary of cleared results
        """
        with self._lock:
            if batch_id:
                if batch_id in self._results:
                    count = len(self._results[batch_id])
                    del self._results[batch_id]
                    return {"cleared_batch": batch_id, "cleared_count": count}
                return {"error": f"Batch {batch_id} not found", "cleared_count": 0}

            # Clear all
            total = sum(len(results) for results in self._results.values())
            self._results.clear()
            return {"cleared_count": total, "remaining_batches": 0}


def _upsert_query_param(url: str, key: str, value: str) -> str:
    """Add or replace query parameter in URL."""
    parsed = urlsplit(url)
    pairs = parse_qsl(parsed.query, keep_blank_values=True)
    updated: list[tuple[str, str]] = []
    replaced = False
    for k, v in pairs:
        if k == key and not replaced:
            updated.append((key, value))
            replaced = True
        elif k != key:
            updated.append((k, v))
    if not replaced:
        updated.append((key, value))
    new_query = urlencode(updated, doseq=True)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, new_query, parsed.fragment))


def get_fuzzer_manager() -> FuzzerManager:
    """Get the global FuzzerManager instance."""
    return FuzzerManager._get_instance()
