import type { LayerKey } from "../hooks/use-tuning-state";
import { RAIN_PARAM_LIMITS, SNOW_FALL_SPEED_MAX } from "../lib/constants";

export type TunableLayerKey = Exclude<LayerKey, "layers">;

export interface ParameterDef {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
}

export interface ParameterGroup {
  name: string;
  layer: TunableLayerKey;
  params: ParameterDef[];
}

export const PARAMETER_GROUPS: ParameterGroup[] = [
  {
    name: "Sky",
    layer: "celestial",
    params: [
      {
        key: "celestialY",
        label: "Sun/Moon Height",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "celestialX",
        label: "Sun/Moon Position",
        min: 0,
        max: 1,
        step: 0.01,
      },
      { key: "sunSize", label: "Sun Size", min: 0.01, max: 0.2, step: 0.005 },
      { key: "moonSize", label: "Moon Size", min: 0.01, max: 0.2, step: 0.005 },
      { key: "moonPhase", label: "Moon Phase", min: 0, max: 1, step: 0.01 },
      { key: "starDensity", label: "Star Density", min: 0, max: 2, step: 0.01 },
      {
        key: "sunGlowIntensity",
        label: "Sun Glow Intensity",
        min: 0,
        max: 6,
        step: 0.05,
      },
      {
        key: "sunGlowSize",
        label: "Sun Glow Size",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "moonGlowIntensity",
        label: "Moon Glow Intensity",
        min: 0,
        max: 6,
        step: 0.05,
      },
      {
        key: "moonGlowSize",
        label: "Moon Glow Size",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "skyBrightness",
        label: "Sky Brightness",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "skySaturation",
        label: "Sky Saturation",
        min: 0,
        max: 2,
        step: 0.01,
      },
      { key: "skyContrast", label: "Sky Contrast", min: 0, max: 2, step: 0.01 },
    ],
  },
  {
    name: "Sun Rays",
    layer: "celestial",
    params: [
      {
        key: "sunRayCount",
        label: "Ray Count",
        min: 0,
        max: 24,
        step: 1,
      },
      {
        key: "sunRayLength",
        label: "Ray Length",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "sunRayIntensity",
        label: "Ray Intensity",
        min: 0,
        max: 3,
        step: 0.01,
      },
      {
        key: "sunRayShimmer",
        label: "Ray Shimmer",
        min: 0,
        max: 5,
        step: 0.05,
      },
      {
        key: "sunRayShimmerSpeed",
        label: "Ray Shimmer Speed",
        min: 0,
        max: 5,
        step: 0.05,
      },
    ],
  },
  {
    name: "Clouds",
    layer: "cloud",
    params: [
      { key: "cloudScale", label: "Scale", min: 0.5, max: 3, step: 0.01 },
      { key: "coverage", label: "Coverage", min: 0, max: 1, step: 0.01 },
      { key: "density", label: "Density", min: 0, max: 2, step: 0.01 },
      { key: "softness", label: "Softness", min: 0, max: 1, step: 0.01 },
      {
        key: "lightIntensity",
        label: "Light Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "ambientDarkness",
        label: "Ambient Darkness",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "backlightIntensity",
        label: "Backlight Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      { key: "windSpeed", label: "Wind Speed", min: 0, max: 2, step: 0.01 },
      {
        key: "windAngle",
        label: "Wind Angle",
        min: -3.14,
        max: 3.14,
        step: 0.01,
      },
      { key: "turbulence", label: "Turbulence", min: 0, max: 1, step: 0.01 },
      {
        key: "sunAzimuth",
        label: "Sun Azimuth",
        min: 0,
        max: 6.28,
        step: 0.01,
      },
      { key: "numLayers", label: "Layers", min: 1, max: 8, step: 1 },
      { key: "layerSpread", label: "Layer Spread", min: 0, max: 1, step: 0.01 },
      { key: "horizonLine", label: "Horizon Line", min: 0, max: 1, step: 0.01 },
      { key: "starSize", label: "Star Size", min: 0, max: 2, step: 0.01 },
      {
        key: "starTwinkleSpeed",
        label: "Star Twinkle Speed",
        min: 0,
        max: 3,
        step: 0.01,
      },
      {
        key: "starTwinkleAmount",
        label: "Star Twinkle Amount",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    name: "Rain",
    layer: "rain",
    params: [
      {
        key: "zoom",
        label: "Zoom",
        min: RAIN_PARAM_LIMITS.zoom.min,
        max: RAIN_PARAM_LIMITS.zoom.max,
        step: 0.01,
      },
      {
        key: "fallingIntensity",
        label: "Falling Intensity",
        min: RAIN_PARAM_LIMITS.fallingIntensity.min,
        max: RAIN_PARAM_LIMITS.fallingIntensity.max,
        step: 0.01,
      },
      {
        key: "fallingSpeed",
        label: "Falling Speed",
        min: RAIN_PARAM_LIMITS.fallingSpeed.min,
        max: RAIN_PARAM_LIMITS.fallingSpeed.max,
        step: 0.1,
      },
      {
        key: "fallingAngle",
        label: "Falling Angle",
        min: RAIN_PARAM_LIMITS.fallingAngle.min,
        max: RAIN_PARAM_LIMITS.fallingAngle.max,
        step: 0.01,
      },
      {
        key: "fallingStreakLength",
        label: "Streak Length",
        min: RAIN_PARAM_LIMITS.fallingStreakLength.min,
        max: RAIN_PARAM_LIMITS.fallingStreakLength.max,
        step: 0.01,
      },
      {
        key: "fallingLayers",
        label: "Layers",
        min: RAIN_PARAM_LIMITS.fallingLayers.min,
        max: RAIN_PARAM_LIMITS.fallingLayers.max,
        step: 1,
      },
      {
        key: "fallingRefraction",
        label: "Refraction",
        min: RAIN_PARAM_LIMITS.fallingRefraction.min,
        max: RAIN_PARAM_LIMITS.fallingRefraction.max,
        step: 0.01,
      },
      {
        key: "fallingWaviness",
        label: "Waviness",
        min: RAIN_PARAM_LIMITS.fallingWaviness.min,
        max: RAIN_PARAM_LIMITS.fallingWaviness.max,
        step: 0.01,
      },
      {
        key: "fallingThicknessVar",
        label: "Thickness Var",
        min: RAIN_PARAM_LIMITS.fallingThicknessVar.min,
        max: RAIN_PARAM_LIMITS.fallingThicknessVar.max,
        step: 0.01,
      },
      {
        key: "glassIntensity",
        label: "Glass Droplets",
        min: RAIN_PARAM_LIMITS.glassIntensity.min,
        max: RAIN_PARAM_LIMITS.glassIntensity.max,
        step: 0.01,
      },
    ],
  },
  {
    name: "Snow",
    layer: "snow",
    params: [
      { key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01 },
      { key: "layers", label: "Layers", min: 1, max: 8, step: 1 },
      {
        key: "fallSpeed",
        label: "Fall Speed",
        min: 0.1,
        max: SNOW_FALL_SPEED_MAX,
        step: 0.1,
      },
      { key: "windSpeed", label: "Wind", min: 0, max: 2, step: 0.01 },
      {
        key: "windAngle",
        label: "Wind Angle",
        min: -3.14,
        max: 3.14,
        step: 0.01,
      },
      {
        key: "windShear",
        label: "Wind Shear",
        min: 0,
        max: 1,
        step: 0.01,
      },
      { key: "turbulence", label: "Turbulence", min: 0, max: 1, step: 0.01 },
      { key: "drift", label: "Drift", min: 0, max: 1, step: 0.01 },
      { key: "flutter", label: "Flutter", min: 0, max: 1, step: 0.01 },
      { key: "flakeSize", label: "Flake Size", min: 0.2, max: 2, step: 0.01 },
      {
        key: "sizeVariation",
        label: "Size Variation",
        min: 0,
        max: 1,
        step: 0.01,
      },
      { key: "opacity", label: "Opacity", min: 0, max: 1, step: 0.01 },
      { key: "glowAmount", label: "Glow", min: 0, max: 1, step: 0.01 },
      { key: "sparkle", label: "Sparkle", min: 0, max: 1, step: 0.01 },
      {
        key: "visibility",
        label: "Visibility",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    name: "Lightning",
    layer: "lightning",
    params: [
      {
        key: "glowIntensity",
        label: "Flash Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "autoInterval",
        label: "Auto Interval",
        min: 1,
        max: 20,
        step: 0.25,
      },
      {
        key: "branchDensity",
        label: "Branch Density",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "displacement",
        label: "Displacement",
        min: 0,
        max: 0.2,
        step: 0.005,
      },
      {
        key: "flashDuration",
        label: "Flash Duration",
        min: 0.05,
        max: 0.5,
        step: 0.01,
      },
      {
        key: "sceneIllumination",
        label: "Scene Illumination",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "afterglowPersistence",
        label: "Afterglow",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    name: "Glass",
    layer: "glass",
    params: [
      { key: "depth", label: "Depth", min: 2, max: 20, step: 1 },
      { key: "strength", label: "Strength", min: 10, max: 120, step: 5 },
      {
        key: "chromaticAberration",
        label: "Chromatic",
        min: 0,
        max: 20,
        step: 1,
      },
      { key: "blur", label: "Blur", min: 0, max: 6, step: 0.5 },
      {
        key: "brightness",
        label: "Brightness",
        min: 0.8,
        max: 1.4,
        step: 0.05,
      },
      { key: "saturation", label: "Saturation", min: 0.5, max: 2.0, step: 0.1 },
    ],
  },
  {
    name: "Post",
    layer: "post",
    params: [
      { key: "haze", label: "Haze", min: 0, max: 1, step: 0.01 },
      {
        key: "hazeHorizon",
        label: "Haze Horizon",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "hazeDesaturation",
        label: "Haze Desaturation",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "hazeContrast",
        label: "Haze Contrast",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "bloomIntensity",
        label: "Bloom Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "bloomThreshold",
        label: "Bloom Threshold",
        min: 0,
        max: 1,
        step: 0.01,
      },
      { key: "bloomKnee", label: "Bloom Knee", min: 0, max: 1, step: 0.01 },
      { key: "bloomRadius", label: "Bloom Radius", min: 0, max: 20, step: 0.5 },
      {
        key: "bloomTapScale",
        label: "Bloom Tap Scale",
        min: 0.5,
        max: 2,
        step: 0.01,
      },
      {
        key: "exposureIntensity",
        label: "Exposure Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "exposureDesaturation",
        label: "Exposure Desaturation",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "exposureRecovery",
        label: "Exposure Recovery",
        min: 0,
        max: 5,
        step: 0.05,
      },
      {
        key: "godRayIntensity",
        label: "God Rays Intensity",
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        key: "godRayDecay",
        label: "God Rays Decay",
        min: 0.8,
        max: 1,
        step: 0.001,
      },
      {
        key: "godRayDensity",
        label: "God Rays Density",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "godRayWeight",
        label: "God Rays Weight",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "godRaySamples",
        label: "God Rays Samples",
        min: 0,
        max: 200,
        step: 1,
      },
    ],
  },
];
