import { CapacitorUpdater } from '@capgo/capacitor-updater';
import { Capacitor } from '@capacitor/core';
import './style.css';
import { FileSharer } from '@capgo/capacitor-file-sharer';

const output = document.getElementById('plugin-output');
const textInput = document.getElementById('file-text');
const shareButton = document.getElementById('share-file');
const saveButton = document.getElementById('save-file');
const versionButton = document.getElementById('get-version');

const setOutput = (value) => {
  output.textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
};

const fileOptions = () => ({
  filename: 'capgo-file-sharer.txt',
  contentType: 'text/plain',
  base64Data: btoa(textInput.value),
  title: 'Capgo File Sharer',
  text: 'Generated by the example app',
});

shareButton.addEventListener('click', async () => {
  try {
    await FileSharer.share(fileOptions());
    setOutput('Share action started.');
  } catch (error) {
    setOutput(`Error: ${error?.message ?? error}`);
  }
});

saveButton.addEventListener('click', async () => {
  try {
    const result = await FileSharer.save({
      ...fileOptions(),
      android: { saveDirectory: 'downloads', relativePath: 'Download/Capgo' },
    });
    setOutput(result);
  } catch (error) {
    setOutput(`Error: ${error?.message ?? error}`);
  }
});

versionButton.addEventListener('click', async () => {
  try {
    const result = await FileSharer.getPluginVersion();
    setOutput(result);
  } catch (error) {
    setOutput(`Error: ${error?.message ?? error}`);
  }
});

if (Capacitor.isNativePlatform()) {
  CapacitorUpdater.notifyAppReady().catch((error) => {
    console.error('Capgo notifyAppReady failed', error);
  });
}
