// @ts-nocheck
// AUTO-GENERATED by `pnpm weather:compile`.
// Source: lib/weather-authoring/weather-widget/weather-data-overlay.tsx
// DO NOT EDIT MANUALLY.

"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef, useState, useCallback } from "react";
import { Sun, Cloud, CloudSun, CloudFog, CloudDrizzle, CloudRain, CloudLightning, Snowflake, CloudHail, Wind, } from "lucide-react";
import { cn } from "./_adapter";
import { getSceneBrightnessFromTimeOfDay, getTimeOfDay, getWeatherTheme, } from "./effects/parameter-mapper";
import { resolveGlassBackdropFilterStyles } from "./effects/glass-style-resolver";
import { useGlassStyles } from "./effects/use-glass-styles";
function getPeakIntensity(timeOfDay) {
    const noonDistance = Math.abs(timeOfDay - 0.5);
    const midnightDistance = Math.min(timeOfDay, 1 - timeOfDay);
    const minDistance = Math.min(noonDistance, midnightDistance);
    return Math.max(0, 1 - minDistance * 4);
}
function sineEasedGradient(x, y, radius, peakOpacity, steps = 8) {
    const stops = [];
    for (let i = 0; i <= steps; i++) {
        const t = i / steps;
        const eased = Math.sin((t * Math.PI) / 2);
        const opacity = peakOpacity * (1 - eased);
        const position = t * 100;
        stops.push(`rgba(255,255,255,${opacity.toFixed(4)}) ${position.toFixed(1)}%`);
    }
    return `radial-gradient(circle ${radius}px at ${x}px ${y}px, ${stops.join(", ")})`;
}
const conditionIcons = {
    clear: Sun,
    "partly-cloudy": CloudSun,
    cloudy: Cloud,
    overcast: Cloud,
    fog: CloudFog,
    drizzle: CloudDrizzle,
    rain: CloudRain,
    "heavy-rain": CloudRain,
    thunderstorm: CloudLightning,
    snow: Snowflake,
    sleet: CloudHail,
    hail: CloudHail,
    windy: Wind,
};
export function observeCardDimensions(element, onResize) {
    if (!element || typeof ResizeObserver !== "function") {
        return () => { };
    }
    const observer = new ResizeObserver(onResize);
    observer.observe(element);
    return () => observer.disconnect();
}
export function WeatherDataOverlay({ location, conditionCode, temperature, tempHigh, tempLow, forecast = [], unit = "fahrenheit", theme: themeProp, timeOfDay: timeOfDayProp, timestamp, className, reducedMotion = false, glassParams, }) {
    const timeOfDay = typeof timeOfDayProp === "number"
        ? timeOfDayProp
        : typeof timestamp === "string"
            ? getTimeOfDay(timestamp)
            : 0.5;
    const [glowState, setGlowState] = useState({
        x: 0,
        y: 0,
        intensity: 0,
    });
    const [cardDimensions, setCardDimensions] = useState({ width: 0, height: 0 });
    const cardRef = useRef(null);
    const containerRef = useRef(null);
    const pendingGlowStateRef = useRef(null);
    const pendingGlowFrameRef = useRef(null);
    const glassEnabled = glassParams?.enabled !== false;
    const glassStyles = useGlassStyles({
        width: cardDimensions.width,
        height: cardDimensions.height,
        depth: glassParams?.depth ?? 3,
        radius: 12,
        strength: glassParams?.strength ?? 75,
        chromaticAberration: glassParams?.chromaticAberration ?? 6,
        blur: glassParams?.blur ?? 1.5,
        brightness: glassParams?.brightness ?? 0.8,
        saturation: glassParams?.saturation ?? 1.3,
        enabled: glassEnabled,
    });
    const updateCardDimensions = useCallback(() => {
        if (cardRef.current) {
            const rect = cardRef.current.getBoundingClientRect();
            setCardDimensions({
                width: Math.round(rect.width),
                height: Math.round(rect.height),
            });
        }
    }, []);
    const hasForecastStrip = forecast.length > 0;
    useEffect(() => {
        updateCardDimensions();
        return observeCardDimensions(cardRef.current, updateCardDimensions);
    }, [hasForecastStrip, updateCardDimensions]);
    const theme = themeProp ??
        getWeatherTheme(getSceneBrightnessFromTimeOfDay(timeOfDay, conditionCode));
    const commitGlowState = useCallback((nextState) => {
        setGlowState((prevState) => {
            if (prevState.x === nextState.x &&
                prevState.y === nextState.y &&
                prevState.intensity === nextState.intensity) {
                return prevState;
            }
            return nextState;
        });
    }, []);
    const cancelPendingGlowFrame = useCallback(() => {
        pendingGlowStateRef.current = null;
        if (pendingGlowFrameRef.current !== null &&
            typeof window !== "undefined" &&
            typeof window.cancelAnimationFrame === "function") {
            window.cancelAnimationFrame(pendingGlowFrameRef.current);
        }
        pendingGlowFrameRef.current = null;
    }, []);
    const scheduleGlowState = useCallback((nextState) => {
        pendingGlowStateRef.current = nextState;
        if (pendingGlowFrameRef.current !== null) {
            return;
        }
        if (typeof window === "undefined" ||
            typeof window.requestAnimationFrame !== "function") {
            pendingGlowStateRef.current = null;
            commitGlowState(nextState);
            return;
        }
        pendingGlowFrameRef.current = window.requestAnimationFrame(() => {
            pendingGlowFrameRef.current = null;
            const pendingState = pendingGlowStateRef.current;
            pendingGlowStateRef.current = null;
            if (pendingState) {
                commitGlowState(pendingState);
            }
        });
    }, [commitGlowState]);
    const clearGlowIntensity = useCallback(() => {
        cancelPendingGlowFrame();
        setGlowState((prevState) => {
            if (prevState.intensity === 0) {
                return prevState;
            }
            return { ...prevState, intensity: 0 };
        });
    }, [cancelPendingGlowFrame]);
    useEffect(() => {
        if (reducedMotion) {
            clearGlowIntensity();
            return;
        }
        const container = containerRef.current;
        if (!container)
            return;
        const handleMouseMove = (e) => {
            if (!cardRef.current)
                return;
            const cardRect = cardRef.current.getBoundingClientRect();
            const clampedX = Math.max(cardRect.left, Math.min(e.clientX, cardRect.right));
            const clampedY = Math.max(cardRect.top, Math.min(e.clientY, cardRect.bottom));
            const distanceX = e.clientX < cardRect.left
                ? cardRect.left - e.clientX
                : e.clientX > cardRect.right
                    ? e.clientX - cardRect.right
                    : 0;
            const distanceY = e.clientY < cardRect.top
                ? cardRect.top - e.clientY
                : e.clientY > cardRect.bottom
                    ? e.clientY - cardRect.bottom
                    : 0;
            const distance = Math.sqrt(distanceX * distanceX + distanceY * distanceY);
            const maxDistance = 150;
            const intensity = Math.max(0, 1 - distance / maxDistance);
            scheduleGlowState({
                x: clampedX - cardRect.left,
                y: clampedY - cardRect.top,
                intensity,
            });
        };
        const handleMouseLeave = () => {
            clearGlowIntensity();
        };
        container.addEventListener("mousemove", handleMouseMove);
        container.addEventListener("mouseleave", handleMouseLeave);
        return () => {
            container.removeEventListener("mousemove", handleMouseMove);
            container.removeEventListener("mouseleave", handleMouseLeave);
            cancelPendingGlowFrame();
        };
    }, [
        reducedMotion,
        clearGlowIntensity,
        scheduleGlowState,
        cancelPendingGlowFrame,
    ]);
    const roundedTemperature = Math.round(temperature);
    const unitSymbol = unit === "celsius" ? "C" : "F";
    const spokenUnit = unit === "celsius" ? "Celsius" : "Fahrenheit";
    const peakIntensity = getPeakIntensity(timeOfDay);
    const isDark = theme === "dark";
    const textPrimary = isDark ? "text-white" : "text-black";
    const textPrimarySoft = isDark ? "text-white/90" : "text-black/85";
    const textSecondary = isDark ? "text-white/80" : "text-black/80";
    const textSubtle = isDark ? "text-white/40" : "text-black/40";
    const baseBgOpacity = isDark ? 0.04 : 0.04;
    const bgOpacity = baseBgOpacity * (1 - peakIntensity * 0.7);
    const midnightDistance = Math.min(timeOfDay, 1 - timeOfDay);
    const baseBlur = isDark ? 2 + midnightDistance * 38 : 24;
    const blurAmount = isDark
        ? baseBlur
        : baseBlur - peakIntensity * (baseBlur - 8);
    const isDawn = timeOfDay > 0.1 && timeOfDay < 0.4;
    const dawnIntensity = isDawn ? 1 - Math.abs(timeOfDay - 0.25) * 4 : 0;
    const forecastTextShadow = dawnIntensity > 0
        ? `0 0.5px 1px rgba(0,0,0,${(dawnIntensity * 0.4).toFixed(2)})`
        : undefined;
    const shadowStyle = isDark
        ? "0 1px 8px rgba(0,0,0,0.3)"
        : "0 1px 8px rgba(255,255,255,0.3)";
    const locationFontSize = "clamp(13px, 7.5cqmin, 17px)";
    const temperatureFontSize = "clamp(48px, 32cqmin, 72px)";
    const degreeFontSize = "clamp(18px, 12cqmin, 28px)";
    const hiLoFontSize = "clamp(11px, 6.5cqmin, 15px)";
    const forecastFontFamily = '"SF Pro Text", Inter, "Noto Sans", system-ui, sans-serif';
    return (_jsxs("div", { ref: containerRef, className: cn("pointer-events-auto absolute inset-0 z-10 flex select-none flex-col", className), children: [_jsx("div", { className: "px-6 pt-6", children: _jsxs("div", { className: "flex flex-col items-start", children: [_jsx("h2", { className: cn("font-medium leading-[1.08] tracking-tight", textSecondary), style: {
                                fontSize: locationFontSize,
                                fontFamily: forecastFontFamily,
                                textShadow: shadowStyle,
                            }, children: location }), _jsxs("div", { className: "-mt-0.5 flex items-start gap-1", children: [_jsx("span", { className: cn("font-[250] tabular-nums leading-[1.02] tracking-[-0.015em]", textPrimarySoft), style: {
                                        fontSize: temperatureFontSize,
                                        fontFamily: forecastFontFamily,
                                        fontFeatureSettings: '"tnum" 1, "case" 1',
                                        textShadow: isDark
                                            ? "0 2px 20px rgba(0,0,0,0.25)"
                                            : "0 2px 20px rgba(255,255,255,0.3)",
                                    }, "aria-hidden": "true", children: roundedTemperature }), _jsxs("span", { className: cn("mt-2 font-[250] tabular-nums", textSecondary), style: {
                                        fontSize: degreeFontSize,
                                        fontFamily: forecastFontFamily,
                                        fontFeatureSettings: '"tnum" 1, "case" 1',
                                    }, "aria-hidden": "true", children: ["\u00B0", unitSymbol] }), _jsxs("span", { className: "sr-only", children: [roundedTemperature, " degrees ", spokenUnit] })] }), _jsxs("div", { className: "mt-0.5 flex items-center gap-3", style: {
                                fontFamily: forecastFontFamily,
                                fontFeatureSettings: '"tnum" 1, "case" 1',
                            }, children: [_jsxs("span", { className: "font-medium tabular-nums", style: { fontSize: hiLoFontSize }, children: [_jsx("span", { className: textSubtle, children: "H " }), _jsxs("span", { className: textPrimary, children: [Math.round(tempHigh), "\u00B0"] })] }), _jsxs("span", { className: "font-medium tabular-nums", style: { fontSize: hiLoFontSize }, children: [_jsx("span", { className: textSubtle, children: "L " }), _jsxs("span", { className: textPrimary, children: [Math.round(tempLow), "\u00B0"] })] })] })] }) }), _jsx("div", { className: "flex-1" }), forecast.length > 0 && (_jsx("div", { className: "px-3 pb-3", children: _jsxs("div", { ref: cardRef, className: "weather-forecast-strip relative hidden", children: [_jsx("div", { className: "pointer-events-none absolute inset-0 z-10 rounded-xl transition-opacity duration-300 ease-out", style: {
                                opacity: glowState.intensity,
                                background: sineEasedGradient(glowState.x, glowState.y, 100, isDark ? 0.6 : 1),
                                mask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
                                maskComposite: "exclude",
                                WebkitMaskComposite: "xor",
                                padding: "0.5px",
                            } }), _jsxs("div", { className: "relative overflow-hidden rounded-xl px-3 py-2.5", style: {
                                backgroundColor: `rgba(255, 255, 255, ${bgOpacity})`,
                                ...resolveGlassBackdropFilterStyles({
                                    glassStyles,
                                    blurAmount,
                                }),
                            }, children: [_jsx("div", { className: "pointer-events-none absolute inset-0 mix-blend-color-dodge transition-opacity duration-300 ease-out", style: {
                                        opacity: glowState.intensity,
                                        background: sineEasedGradient(glowState.x, glowState.y, 120, isDark ? 0.06 : 0.15),
                                    } }), _jsx("div", { className: "relative flex items-center justify-between", children: forecast.slice(0, 5).map((day, index) => {
                                        const DayIcon = conditionIcons[day.conditionCode];
                                        return (_jsxs("div", { className: "flex flex-1 flex-col items-center gap-0.5", style: {
                                                fontFamily: forecastFontFamily,
                                                fontFeatureSettings: '"tnum" 1, "case" 1',
                                                textShadow: forecastTextShadow,
                                            }, children: [_jsx("span", { className: cn("text-[10px] uppercase tracking-[0.08em]", index === 0 ? "font-semibold" : "font-medium", textPrimary), children: day.label }), _jsx(DayIcon, { className: cn("my-0.5 size-5", textPrimary, index === 0 ? "opacity-100" : "opacity-70", "weather-forecast-icon hidden"), strokeWidth: 1.5, "aria-hidden": "true" }), _jsxs("div", { className: "flex flex-col items-center gap-0.5", children: [_jsxs("span", { className: cn("text-[15px] tabular-nums leading-[1.2] tracking-[-0.01em]", index === 0 ? "font-semibold" : "font-medium", textPrimary), children: [Math.round(day.tempMax), "\u00B0"] }), _jsxs("span", { className: cn("font-normal text-[12px] tabular-nums leading-[1.3]", textPrimary), children: [Math.round(day.tempMin), "\u00B0"] })] })] }, `${day.label}-${index}`));
                                    }) })] })] }) })), _jsx("style", { children: `
        @container weather (min-height: 245px) {
          .weather-forecast-strip {
            display: block !important;
          }
        }
        @container weather (min-height: 280px) {
          .weather-forecast-icon {
            display: block !important;
          }
        }
      ` })] }));
}
