"""initial schema

Revision ID: 393d982aee01
Revises: 
Create Date: 2026-07-29 11:45:33.491991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393d982aee01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_edges_run_id'), 'agent_edges', ['run_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_run_id'), 'agents', ['run_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('llm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proxy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_run_id'), 'chat_messages', ['run_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=False),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_request', sa.Text(), nullable=True),
    sa.Column('evidence_response', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_session_id'), 'findings', ['session_id'], unique=False)
    op.create_table('hosts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_session_id'), 'hosts', ['session_id'], unique=False)
    op.create_table('listeners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('bind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listeners_session_id'), 'listeners', ['session_id'], unique=False)
    op.create_table('loot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loot_session_id'), 'loot', ['session_id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_key', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_check', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_entries_session_id'), 'proxy_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_proxy_entries_ts'), 'proxy_entries', ['ts'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('elapsed_sec', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('budget_tokens', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_session_id'), 'runs', ['session_id'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('running_sessions', sa.Integer(), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('roe', sa.Text(), nullable=True),
    sa.Column('active_run_id', sa.String(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shells',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('remote_addr', sa.String(), nullable=True),
    sa.Column('pty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shells_session_id'), 'shells', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shells_session_id'), table_name='shells')
    op.drop_table('shells')
    op.drop_table('sessions')
    op.drop_table('servers')
    op.drop_index(op.f('ix_runs_session_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_proxy_entries_ts'), table_name='proxy_entries')
    op.drop_index(op.f('ix_proxy_entries_session_id'), table_name='proxy_entries')
    op.drop_table('proxy_entries')
    op.drop_table('proxies')
    op.drop_table('providers')
    op.drop_index(op.f('ix_loot_session_id'), table_name='loot')
    op.drop_table('loot')
    op.drop_index(op.f('ix_listeners_session_id'), table_name='listeners')
    op.drop_table('listeners')
    op.drop_index(op.f('ix_hosts_session_id'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_findings_session_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chat_messages_run_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_agents_run_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_edges_run_id'), table_name='agent_edges')
    op.drop_table('agent_edges')
    # ### end Alembic commands ###
